"use strict";
/**
 * XKCD
 * Webcomic of romance, sarcasm, math, and language.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var Comic = /** @class */ (function () {
    function Comic() {
    }
    Comic.getAttributeTypeMap = function () {
        return Comic.attributeTypeMap;
    };
    Comic.discriminator = undefined;
    Comic.attributeTypeMap = [
        {
            "name": "alt",
            "baseName": "alt",
            "type": "string"
        },
        {
            "name": "day",
            "baseName": "day",
            "type": "string"
        },
        {
            "name": "img",
            "baseName": "img",
            "type": "string"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "month",
            "baseName": "month",
            "type": "string"
        },
        {
            "name": "news",
            "baseName": "news",
            "type": "string"
        },
        {
            "name": "num",
            "baseName": "num",
            "type": "number"
        },
        {
            "name": "safeTitle",
            "baseName": "safe_title",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "transcript",
            "baseName": "transcript",
            "type": "string"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "string"
        }
    ];
    return Comic;
}());
exports.Comic = Comic;
